export const CHANGE_CONFIG = 'CHANGE_CONFIG'
export const UPDATE_PUBLIC_KEY = 'UPDATE_PUBLIC_KEY'

export const INITIALISE = 'INITIALISE'
export const INITIALISE_SUCCESS = 'INITIALISE_SUCCESS'
export const INITIALISE_ERROR = 'INITIALISE_ERROR'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const POST_LIST = 'POST_LIST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_DETAILS = 'POST_DETAILS'
export const POST_ADDED = 'POST_ADDED'
export const POST_DELETED = 'POST_DELETED'

export const TOQQN_STATS = 'TOQQN_STATS'
export const NEWS_LIST = 'NEWS_LIST'
export const ANNOUNCEMENT_LIST = 'ANNOUNCEMENT_LIST'
export const HALL_OF_FAME_LIST = 'HALL_OF_FAME_LIST'
export const TRENDING_COMMUNITY_LIST = 'TRENDING_COMMUNITY_LIST'

export const COMMUNITY_DETAILS = 'COMMUNITY_DETAILS'
export const COMMUNITY_LIST = 'COMMUNITY_LIST'
export const COMMUNITY_ADDED = 'COMMUNITY_ADDED'

export const ERROR_RESPONSE = 'ERROR_RESPONSE'
